config/routes.rb
Rails.application.routes.draw do
  get "checkout", to: "checkout#show"
  get "success", to: "checkout#success", as: "success"
  get "cancel", to: "checkout#cancel", as: "cancel"
  get 'order/index'
  get 'order/show'
  get 'user/index'
  get 'companies/index'
  get 'platform/index'
  resources :games, only: [:index, :show] do
    collection do
      get "search"
    end
  end
  get 'pages/:permalink' => "pages#permalink", as: 'permalink'
  get 'checkout/index'
  post 'checkout/index'
  post 'checkout/update_tax', to: 'checkout#update_tax', as: 'update_tax'
  post 'games/add_to_cart/:id', to: 'games#add_to_cart', as: 'add_to_cart'
  post 'games/remove_quantity_from_cart/:id', to: 'games#remove_quantity_from_cart', as: 'remove_quantity_from_cart'
  delete 'games/remove_from_cart/:id', to: 'games#remove_from_cart', as: 'remove_from_cart'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  authenticated :user do
    root to: 'games#index', as: :root_app
  end
  resources :genres
  resources :companies
  #resources :games


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  root to: 'games#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :province

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :games
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :genre
  belongs_to :company
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :games
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :order_status
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :game
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders

  def to_s
    status
  end
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :games
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :addresses
  has_one :province

  def to_s
    email
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :authenticate_user!
  def index
    if !params[:province] || params[:province].blank?
      if current_user && !current_user.blank? && !current_user.province_id.nil?
        params[:province] = current_user.province_id
      else
        params[:province] = 1
      end
    end
    @tax_percent = update_tax()
  end

  def show
    item_list = []

    session[:cart_id].each_with_index do |i, index|
      item = Game.find(i)
      item_list.append(
      {
        price_data: {
          currency: 'cad',
          unit_amount: item.price,
          product_data: {
            name: item.name,
          },
          tax_behavior: 'exclusive',
        },
        quantity: session[:cart_quantity][index]
      })
    end

    domain = "http://localhost:3000/"
    Stripe.api_key = "sk_test_51M4ZdDE69JA1nsv1EMLUX2G7rpyJHkS7CnWPBsWcJZh9kFocuus6Ulw0YED808WfVzMQwBstpoYxKWfaGRUrtk1z00tHYaXq0w"
    session = Stripe::Checkout::Session.create({
      # line_items: [{
      #   price: 'price_1MDiKQE69JA1nsv1boNdCngc',
      #   quantity: 1,
      # }],
      line_items: item_list,
      mode: 'payment',
      success_url: domain + 'success',
      cancel_url: domain,
      shipping_address_collection: {allowed_countries: ['CA']},
      automatic_tax: {enabled: true},
    })
    redirect_to session.url, allow_other_host: true
  end


  def success
    if(session[:cart_id] && !session[:cart_id].blank?)
      games = Game.find(session[:cart_id])
      sub_total = 0
      games.each_with_index do |g, i|
        sub_total = sub_total + (g.price * session[:cart_quantity][i])
      end
      tax = calculate_tax(current_user.province_id, sub_total)

      new_order = Order.create(
        sub_total: sub_total,
        taxes: tax,
        order_total: (sub_total + tax),
        user_id: current_user.id,
        order_status: OrderStatus.find_by(code: 'PEN-S'),
        total_payed: (sub_total + tax)
      )

      games.each_with_index do |g, i|
        new_order.order_items.create(
          game_id: g.id,
          unit_price: g.price,
          quantity: session[:cart_quantity][i]
        )
      end
      session[:cart_quantity] = []
      session[:cart_id] = []
    end
  end

  private
  def update_tax
    province = Province.find(params[:province])

    return province.hst + province.gst + province.pst
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/platform_helper.rb
module PlatformHelper
end

app/views/checkout/cancel.html.erb
<h1>CANCEL</h1>

app/views/checkout/create.js.erb
console.log("<%= @game.name %>");

app/views/checkout/index.html.erb
<%
subTotal = 0
tax_percent = 0
tax = 0%>

<div class= "container">
<h1>Invoice</h1>
<%= form_with method: :get do |f|%>
<div class="select">
 <%= f.select 'province', options_for_select(Province.all.map{|el| [el.name, el.id]}, params[:province]), class: "select"%>
 </div>
 <%= f.button "Update Tax", class: "button is-link"%>
<% end %>
<table class="table">
<th>Product</th>
<th>Quantity</th>
<th>Price</th>

<tbody>
  <% @cart_id.each do |item|%>
  <% index = session[:cart_id].index(item.id)%>
  <tr>
    <td>
      <%= link_to item.name, item%>
    </td>
    <td>
      <%= @cart_quantity[index] %>
    </td>
    <td>
      <%=number_to_currency (@cart_quantity[index] * item.price)/100.0%>
      <% subTotal = subTotal + @cart_quantity[index] * item.price%>
    </td>

  </tr>
  <% end %>
  <tr>
    <td>
    </td>
     <td>
      Sub Total
    </td>
    <td>
    <%= number_to_currency subTotal/100.0%>
    </td>
  </tr>
  <tr>
    <td>
    </td>
     <td>
      Taxes
    </td>
    <td>
    <% tax = (subTotal * @tax_percent.to_f)%>
    <%= number_to_currency tax/100.0%>
    </td>
  </tr>
  <tr>
    <td>
    </td>
    <td>
      Total
    </td>
    <td>
    <%= number_to_currency (subTotal + tax)/100.0%>
    </td>
  </tr>
</tbody>
</table>

<%= button_to 'Checkout', checkout_path, data: {turbo: false}, method: :get, class: "button is-link"%>
</div>

app/views/checkout/success.html.erb
<h1>Success</h1>