config/routes.rb
Rails.application.routes.draw do
  get "checkout", to: "checkout#show"
  get "success", to: "checkout#success", as: "success"
  get "cancel", to: "checkout#cancel", as: "cancel"
  get 'order/index'
  get 'order/show'
  get 'user/index'
  get 'companies/index'
  get 'platform/index'
  resources :games, only: [:index, :show] do
    collection do
      get "search"
    end
  end
  get 'pages/:permalink' => "pages#permalink", as: 'permalink'
  get 'checkout/index'
  post 'checkout/index'
  post 'checkout/update_tax', to: 'checkout#update_tax', as: 'update_tax'
  post 'games/add_to_cart/:id', to: 'games#add_to_cart', as: 'add_to_cart'
  post 'games/remove_quantity_from_cart/:id', to: 'games#remove_quantity_from_cart', as: 'remove_quantity_from_cart'
  delete 'games/remove_from_cart/:id', to: 'games#remove_from_cart', as: 'remove_from_cart'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  authenticated :user do
    root to: 'games#index', as: :root_app
  end
  resources :genres
  resources :companies
  #resources :games


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  root to: 'games#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :province

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :games
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :genre
  belongs_to :company
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :games
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :order_status
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :game
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders

  def to_s
    status
  end
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :games
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :addresses
  has_one :province

  def to_s
    email
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show add_to_cart ]
  before_action :initialize_session
  before_action :increment_visit_count, only: %i[index]
  before_action :load_cart
  # GET /games or /games.json
  def index
    @games = Game.order(name: :asc).page(params[:page])
  end

  # GET /games/1 or /games/1.json
  def show
  end





  def search
    search_param = "%#{params[:keywords]}%"
    if params[:genres].blank? && params[:keywords].blank?
    redirect_to root_path and return
    elsif params[:genres].blank?
      @games = Game.where("lower(name) LIKE ? OR lower(description) LIKE ?", search_param, search_param )
    elsif params[:keywords].blank?
      @games = Game.where(genre_id: params[:genres])
    else
      @games = Game.where(genre_id: params[:genres]).where("lower(name) LIKE ? OR lower(description) LIKE ?", search_param, search_param )
    end
  end
  # GET /games/new
  # def new
  #   @game = Game.new
  #   @genre = Genre.all.map{|g| [ g.name, g.id ] }
  # end

  # GET /games/1/edit
  # def edit
  #   @game = Game.find(params[:id])
  #   @genre = Genre.all.map{|g| [ g.name, g.id ] }
  # end

  # POST /games or /games.json
  # def create
  #   @game = Game.new(game_params)

  #   respond_to do |format|
  #     if @game.save
  #       format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
  #       format.json { render :show, status: :created, location: @game }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @game.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /games/1 or /games/1.json
  # def update
  #   respond_to do |format|
  #     if @game.update(game_params)
  #       puts @game
  #       format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
  #       format.json { render :show, status: :ok, location: @game }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @game.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /games/1 or /games/1.json
  # def destroy
  #   @game.destroy

  #   respond_to do |format|
  #     format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private

    def initialize_session
      session[:visit_count] ||= 0
    end

    def increment_visit_count
      session[:visit_count] += 1
      @visit_count = session[:visit_count]
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:name, :description, :publish_date, :price, :genre_id, :company_id)
    end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  before_action :authenticate_user!
  def index
    @orders = Order.where(user_id: current_user.id)
  end

  def show
    order = Order.find(params[:format])
    return unless order.user == current_user

    @order = order
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/platform_helper.rb
module PlatformHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :publish_date, style: "display: block" %>
    <%= form.date_field :publish_date %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :genre, style: "display: block" %>
    <%= form.select(:genre_id, @genre) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">

<h1 class="title is-4"><%= game.name %></h1>
  <p>
    <strong>Genre:</strong>
    <%# <%= game.genre.name %>
    <% if @game != nil %>
    <%= link_to @game.genre.name, @game.genre%>
    <% elsif game != nil %>
    <%= link_to game.genre.name, game.genre%>
    <% end %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= game.description %>
  </p>

  <p>
    <strong>Publish date:</strong>
    <%= game.publish_date %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= number_to_currency game.price/100.0 %>
  </p>



</div>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="title is-1">Games</h1>

<%= paginate @games %>
  <%= page_entries_info @games %>
  <div><br></div>
<div id="games">
  <% @games.each do |game| %>
    <%= render game %>
    <p>
      <%= link_to "Show this game", game %>
    </p>
    <%# <p><%= link_to "add to cart", add_to_cart_path(game.id), method: :post </p> %>
    <% if !@cart_id.blank? && @cart_id.include?(game)%>
      <p><%= button_to 'add 1 quantity to cart', add_to_cart_path(game.id),class: "button is-small"%></p>
      <p><%= button_to 'remove 1 quantity from cart', remove_quantity_from_cart_path(game.id),class: "button is-small" %></p>
      <p><%= button_to 'remove from cart', remove_from_cart_path(game.id), method: :delete, class: "button is-small" %></p>
    <% else %>
      <%= button_to 'add to cart', add_to_cart_path(game.id), class: "button is-small" %>
    <% end %>
    <br>
  <% end %>
</div>

<%# <%= link_to "New game", new_game_path %>

app/views/games/search.html.erb
<div class="columns">
  <div class="column">
    <h2 class="title is-2"><%= params[:keywords] %> </h2>
    <ol class="ml-5">
      <% @games.each do |game| %>
        <li>
          <%= link_to game.name, game %>
          <em>(<%= game.genre.name %>)</em>
        </li>
      <% end %>
    </ol>
  </div>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @game %>

<div>
  <% if !@cart.blank? && @cart.include?(@game)%>
    <p><%= button_to 'remove from cart', remove_from_cart_path(@game.id), method: :delete, class: "button is-small"%></p>
  <% else %>
    <%= button_to 'add to cart', add_to_cart_path(@game.id), class: "button is-small" %>
  <% end %>
  <%# <%= link_to "Edit this game", edit_game_path(@game) %>
  <%= link_to "Back to games", games_path, class: "button is-link" %>

  <%# <%= button_to "Destroy this game", @game, method: :delete %>
</div>

app/views/order/index.html.erb
<h1>All Orders</h1>

<table class="table">
  <thead>
    <th>Order Number</th>
    <th>Order Date</th>
    <th>Last Update</th>
    <th>Order Status</th>
    <th>Taxes</th>
    <th>Total Cost</th>
  </thead>

  <tbody>
    <% @orders.each do |i|%>
      <tr>
        <td><%=link_to i.id, order_show_path(i) %></td>
        <td><%= i.created_at %></td>
        <td><%= i.updated_at %></td>
        <td><%= i.order_status %></td>
        <td><%= number_to_currency i.taxes/ 100.0 %></td>
        <td><%= number_to_currency i.order_total/100.0 %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/order/show.html.erb
<%
subTotal = 0
tax_percent = 0
tax = 0%>

<div class= "container">
<h1 class="title is-1">Order Number: <%= @order.id %></h1>
<h2 class="title is-2">Order Status: <%= @order.order_status%></h2>
<table class="table">
<thead>
  <th>Product</th>
  <th>Quantity</th>
  <th>Price</th>
</thead>
<tbody>
  <% @order.order_items.each do |item|%>
  <tr>
    <td>
      <%= link_to item.game.name, item.game%>
    </td>
    <td>
      <%= item.quantity %>
    </td>
    <td>
      <%=number_to_currency (item.quantity * item.unit_price)/100.0%>
      <% subTotal = subTotal + item.quantity * item.unit_price%>
    </td>

  </tr>
  <% end %>
  <tr>
    <td>
    </td>
     <td>
      Sub Total
    </td>
    <td>
    <%= number_to_currency subTotal/100.0%>
    </td>
  </tr>
  <tr>
    <td>
    </td>
     <td>
      Taxes
    </td>
    <td>
    <%= number_to_currency @order.taxes/100.0%>
    </td>
  </tr>
  <tr>
    <td>
    </td>
    <td>
      Total
    </td>
    <td>
    <%= number_to_currency (@order.order_total)/100.0%>
    </td>
  </tr>
</tbody>
</table>