config/routes.rb
Rails.application.routes.draw do
  get "checkout", to: "checkout#show"
  get "success", to: "checkout#success", as: "success"
  get "cancel", to: "checkout#cancel", as: "cancel"
  get 'order/index'
  get 'order/show'
  get 'user/index'
  get 'companies/index'
  get 'platform/index'
  resources :games, only: [:index, :show] do
    collection do
      get "search"
    end
  end
  get 'pages/:permalink' => "pages#permalink", as: 'permalink'
  get 'checkout/index'
  post 'checkout/index'
  post 'checkout/update_tax', to: 'checkout#update_tax', as: 'update_tax'
  post 'games/add_to_cart/:id', to: 'games#add_to_cart', as: 'add_to_cart'
  post 'games/remove_quantity_from_cart/:id', to: 'games#remove_quantity_from_cart', as: 'remove_quantity_from_cart'
  delete 'games/remove_from_cart/:id', to: 'games#remove_from_cart', as: 'remove_from_cart'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  authenticated :user do
    root to: 'games#index', as: :root_app
  end
  resources :genres
  resources :companies
  #resources :games


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  root to: 'games#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :province

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :games
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :genre
  belongs_to :company
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :games
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  belongs_to :order_status
  belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :game
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders

  def to_s
    status
  end
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :games
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :addresses
  has_one :province

  def to_s
    email
  end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/platform_helper.rb
module PlatformHelper
end

app/views/layouts/_cart.html.erb
<details>
  <summary>Shopping Cart [<%= @cart_id.count%>]</summary>
  <% if @cart_id.blank? %>
    <p>No items in cart.</p>
  <% else %>
  <% count = 0%>
  <ul>
    <% @cart_id.each do |item|%>

      <li><%= item.name %> x <%= @cart_quantity[count] %>
        <%= button_to 'add 1 quantity to cart', add_to_cart_path(item.id), method: :post, class: "button is-small" %>
        <%= button_to 'remove 1 quantity from cart', remove_quantity_from_cart_path(item.id), method: :post, class: "button is-small" %>
        <%= button_to 'remove from cart', remove_from_cart_path(item.id), method: :delete, class: "button is-small" %>
      </li>
      <% count += 1%>
    <% end %>
  </ul>

  <% end %>
</details>
<%= button_to 'checkout', checkout_index_path, method: :get, class: "button is-link" %>
<br>

app/views/layouts/_navbar.html.erb
<header>
  <section class="section">
  <div class="container">
  <nav class="navbar  has-background-light" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="https://bulma.io">
        <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
      </a>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <%= link_to "All Games", games_path, class: "navbar-item" %>


        <%= link_to "All Companies", companies_path, class: "navbar-item" %>
        <div class="navbar-item has-dropdown is-hoverable">
          <%= link_to "All Genres", genres_path, class: "navbar-link" %>

          <div class="navbar-dropdown">
            <% @nav_genres.each do |genre|%>
            <%= link_to genre.name, genre, class: "navbar-item" %>
            <% end %>
          </div>
        </div>
        <div class="navbar-item has-dropdown is-hoverable">
          <%= link_to "More", "", class: "navbar-link" %>
          <div class="navbar-dropdown">

                    <% Page.all.each do | page |%>
                      <%= link_to page.title, permalink_path(page.permalink), class: "navbar-item"  %>
                    <% end %>
          </div>
        </div>
      </div>

      <% if user_signed_in? %>
        <div class="navbar-item has-dropdown is-hoverable">
          <%= link_to current_user.email, "", :class => 'navbar-link' %>

          <div class="navbar-dropdown">
            <%= link_to 'My Orders', order_index_path, :class => 'navbar-item' %>
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-item' %>
            <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, :class => 'navbar-item'  %>
          </div>
        </div>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-item'  %>
        <%= link_to "Login", new_user_session_path, :class => 'navbar-item'  %>
      <% end %>

      <%# <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <a class="button is-primary">
              <strong>Sign up</strong>
            </a>
            <a class="button is-light">
              Log in
            </a>
          </div>
        </div>
      </div>
    </div> %>
</nav>
  </div>
  </section>

</header>


app/views/layouts/_searchbar.html.erb
<div class="searchBar">
  <% if controller_name == "characters" %>
      <%= form_with(url: search_characters_path, method: :get, local: true) do %>
          <div class="field is-ground mb-5">
            <div class="control is-expanded">
              <%= text_field_tag(:keywords, nil, class: "input", placeholder: 'Search For Characters') %>
            </div>
            <div class="control">
              <%=submit_tag("Search", class: "button")%>
            </div>
          </div>
        <% end %>
      <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-background-light">
  <head>
    <title>GamesSeller</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
  <section class="section">
  <div class="container">
    <%= render "layouts/navbar" %>

    <%= form_with(url: search_games_path, method: :get, local: true) do %>
          <div class="field is-ground mb-5">
            <div class="control is-expanded">
              <%= text_field_tag(:keywords, nil, class: "input", placeholder: 'Search For Games') %>
              <div class="select">
              <%= select_tag 'genres', options_for_select(Genre.all.map{|el| [el.name, el.id]}), :prompt => "All Genres", class: "select" %>
              </div>
            </div>
            <div class="control">
              <%=submit_tag("Search", class: "button is-link")%>
            </div>
          </div>
      <% end %>
    <% if controller_name != "checkout" %>
      <%= render "layouts/cart" %>
    <% end %>

    <%# <% if notice %>
      <%# <p class="alert alert-success"><% notice </p> %>
    <%# <% end %>
    <%# <% if alert %>
      <%# <p class="alert alert-danger"><%= alert </p> %>
    <%# <% end %>
    <%= yield %>
  </div>
  </section>

  </body>
</html>

app/views/pages/permalink.html.erb
<div>
  <h1 class="title is-1"><%=@page.title%></h1>

  <p>
    <%= @page.content %>
  </p>

</div>